### ISSUE TITLE
BUG: Some Open Source sections are not opened while searching.

### ISSUE THREAD

**Issue by itskundanhere** [andoriyaprashant/OpSo#329] opened 2024-10-05 19:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/user-attachments/assets/a963bae8-a579-4760-b3a2-337a7c2b9ce1

On searching the Open Source sections, some of the section are  **not** opened like: **Summer of Bitcoin, Outreachy, Open Source of Code** and rest of the sections are opened.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RebellionR2** [comment] 2024-10-06 16:42
I would like to solve this issue, Kindly assign to me. I am a Gssoc-ext contributor. I just ran this app locally and the issue is still there , Summer of Bitcoin is not opening when clicked

**Closed** 2024-10-14 18:51 UTC
Labels: bug, good first issue, hacktoberfest, gssoc-ext
